name: Action On Push
run-name: Сборка и тестирование проекта
on: 
  [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./computerUniverse/
    steps:
    - name: Копирование
      uses: actions/checkout@v4

    - name: Установка node
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: './computerUniverse/package-lock.json'
        node-version: 9.1.x
        cache: npm 

    - name: Установка зависимостей
      run: npm i

    - name: Сборка проекта
      run: npm run build
  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./computerUniverse/
    steps: 
    - name: Копирование
      uses: actions/checkout@v4

    - name: Установка node
      uses: actions/setup-node@v3
      with:
        cache-dependency-path: './computerUniverse/package-lock.json'
        node-version: 9.1.x
        cache: npm 

    - name: Установка зависимостей
      run: npm i

    - name: Запуск тестов
      run: npm run test:unit