name: Deploy On Pages
run-name: Публикация на Github Pages
on:
  push:
    branches:
      - main

permissions: 
  contents: write


jobs:
  gh-pages-deploy:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./computerUniverse/
    steps:
      - name: Копирование
        uses: actions/checkout@v4

      - name: Установка node
        uses: actions/setup-node@v3
        with:
          cache-dependency-path: './computerUniverse/package-lock.json'
          node-version: 20.1.x
          cache: npm 

      - name: Установка зависимостей
        run: npm i --legacy-peer-deps

      - uses: actions/checkout@v2
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'ErikMak'
          reponame: 'cu_termproject'
          token: ${{ secrets.GITHUB_TOKEN }}