name: Deploy On GitPages
run-name: Публикация на GitHub Pages
on: 
  pull_request:
    branches:
      - main

permissions: 
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps: 
    - name: Копирование
      uses: actions/checkout@v4
      run: cd computerUniverse
      
    - name: Сборка и публикация
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'ErikMak'
        reponame: 'cu-termproject'
        token: ${{ secrets.GITHUB_TOKEN }} 